### ISSUE TITLE
[Enhancement] Compatibility with more MIDI controllers

### ISSUE THREAD

**Issue by nuess0r** [praxis-live/praxiscore#34]
I was playing around with the example "3 audio gui" and tried to map my MIDI DJ controller to it.

Thanks for the useful "last message" output in the MIDI root node.

From the PraxisLive GUI and manual it was unclear what is expected in the MIDI editor for the field controller.

I then searched the source to understand how the MIDI message is parsed (to be found in 
https://github.com/praxis-live/praxiscore/blob/fd8bf129fd8b458e8a063a736c9b75088c84c509/praxiscore-midi/src/main/java/org/praxislive/midi/components/MidiControlIn.java#L131).

My problem is now, that praxiscore only supports MIDI messages of type CONTROL_CHANGE but my DJ controller sends NOTE_ON and NOTE_OFF messages on key press/release.

It would be nice, if the MIDI mapping editor would allow to select as well the defined message types in the  [javax.sound.midi.ShortMessage class](https://docs.oracle.com/javase/7/docs/api/javax/sound/midi/ShortMessage.html)

**Comment by neilcsmith-net** [comment]
Yes, the controller parameter is the controller number, as only control change is supported.

For v6 MIDI will probably be moved out into codeable custom components. An addition coming soon in v5.3 should make it easier to code a data component that can do whatever you want with MIDI. Once out I'll update this with info.

**Comment by neilcsmith-net** [comment]
Also, see if you can find a utility that will map MIDI to OSC - that's what a few other people use currently, and it's the more flexible option.
